name: clock_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.4+5

environment:
  sdk: '>=3.1.0-128.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #Localization
  easy_localization: ^3.0.2

  #State Management
  provider: ^6.0.5

  #Utils
  kartal:
  intl: ^0.18.1
  shared_preferences: ^2.2.0
  wakelock: ^0.6.2
  audioplayers: ^5.0.0

  #UI Utils
  awesome_snackbar_content: ^0.1.3
  device_preview: ^1.1.0

  #Icon
  flutter_svg: ^2.0.7
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1

#Splash Screen
flutter_native_splash:
  image: "assets/icons/app_icon.png"
  color: "#FFB102"

#Icon
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/icons/
  - assets/theme/
  - assets/theme/ipad/
  - assets/json/
  - assets/voice/
  - assets/language/
